# Análisis espacial ráster con R

##### Priscilla Minotti

##### priscilla.minotti@gmail.com

## ¿Por qué uso R?

 - Flujo de trabajo simple y programático para trabajar con datos ráster multitemporales

#### 4 ejemplos

- Descarga de datos y preprocesamiento de productos MODIS
- Estadísticas temporales per pixel
- Muchísimas opciones de análisis mediante algoritmos de aprendizaje automático
- Visualización con Leaflet

## Descarga de datos y preprocesamiento de productos MODIS

#### Paquete MODIStsp L. Busetto, L. Ranghetti(2016)
https://github.com/ropensci/MODIStsp

- Requiere GDAL (instalado) y GTK+ (mapedit)
- Selección x producto, sensor, variable periodo,región, índices espectrales, indicadores de calidad
- Descarga y preprocesaHDFs, genera rasters físicos (tif) o virtuales (serie de tiempo)

```
#interactivo
MODIStsp()
```
```
#no interactivo
```

### descarga.json

```
(EVIstack)
class : RasterStack
dimensions : 3600, 7200, 25920000, 188 (nrow, ncol, ncell, nlayers)
resolution : 0.05, 0.05 (x, y)
extent : -180, 180, -90, 90 (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat+ellps=clrk66 +no_defs
names : MYD13C2_EVI_2002_182, MYD13C2_EVI_2002_213, MYD13C2_EVI_2002_244, MYD13C2_EVI_2002_274,
MYD13C2_EVI_2002_305, MYD13C2_EVI_2002_335, MYD13C2_EVI_2003_001, MYD13C2_EVI_2003_032, MYD13C2_EVI_2003_060,
MYD13C2_EVI_2003_091, MYD13C2_EVI_2003_121, MYD13C2_EVI_2003_152, MYD13C2_EVI_2003_182, MYD13C2_EVI_2003_213,
MYD13C2_EVI_2003_244, ...
min values : -32768, -32768, -32768, -32768, -32768, - 3 2768, -32768, -32768,
32768, -32768, -32768, -32768, -32768, -32768, -32768, ...
maxvalues : 32767, 32767, 32767, 32767, 32767, 3 2767, 32767, 32767,
32767, 32767, 32767, 32767, 32767, 32767, 32767, ...

###Lectura y preparación del stack temporal 

####Paquete raster Robert J. Hijmans(2019)

```
plot(EVIstack[[10:12]])
```
```
plot(EVIstack[[c(1,4,8,12)]])
```

```
plotRGB(EVIstack,1,90,180, stretch='hist')

```

```
pampa<-crop(EVIstack, drawExtent())


``````
plot(EVIstack[[10]])

```

```
(EVIpampa)
**class** : RasterBrick
**dimensions** : 203, 204, 41412, 188 (nrow, ncol, ncell, nlayers)
**resolution** : 0.05, 0.05 (x, y)
**extent** : -64.9, -54.7, -39.9, -29.75 (xmin, xmax, ymin, ymax)
**coord. ref.** : +proj=longlat+ellps=clrk66 +no_defs
**data source** :
C:/Users/Admin/AppData/Local/Temp/RtmpMTLbjX/raster/r_tmp_2019-
04 - 10_234525_9800_86346.grd
**names** : MYD13C2_EVI_2002_182, MYD13C2_EVI_2002_213,
MYD13C2_EVI_2002_244, MYD13C2_EVI_2002_274,
MYD13C2_EVI_2002_305, MYD13C2_EVI_2002_335,
MYD13C2_EVI_2003_001, MYD13C2_EVI_2003_032,
MYD13C2_EVI_2003_060, MYD13C2_EVI_2003_091,
MYD13C2_EVI_2003_121, MYD13C2_EVI_2003_152,
MYD13C2_EVI_2003_182, MYD13C2_EVI_2003_213,
MYD13C2_EVI_2003_244, ...
**min values** : -1810, -1367, -1466, -1419,
1646, -1421, -1443, -1084, -1646,
1220, -1076, -996, -1948, -1676,
1419, ...
**maxvalues** : 5666, 5334, 5573, 5863,
6107, 7818, 7865, 7850, 7121,
5737, 5358, 5350, 5777, 4708,
4909, ...
```


```
mediaEVI<-mean(EVIpampa[[1:180]])
```
## Estadísticas temporales per pixel

##### Paquete rasterVis Oscar PerpinanLamigueiro

```
library(rasterVis)
HumCol <-rasterTheme(region=rev(brewer.pal(10,"Blues")))
pltEVImedia<-levelplot(mediaEVI, margin=F,
par.settings=HumCol,main="EVI medio 2002-2017")
pltEVImedia
```
```
library(remote)
anomEVI<-deseason(EVIpampa[[1:180]], 12)
anomneg<-sum(anomEVI<0)
```
###Estadísticas temporales per pixel

##### Paquete remote Tim Appelhans, FlorianDetsch, Thomas Nauss

HumCol <-rasterTheme(region=rev(brewer.pal(10,"Blues")))

titu<-paste("anomalia",names(EVIpampa[[10]]), sep=" ")
Plt-EVIanom<-levelplot(anomEVI[[10]], margin=F, par.settings=HumCol,main=titu)
Plt-EVIanom

Plt-anomneg<-levelplot(anomneg, margin=F, par.settings=HumCol,main="Suma
Anomaliasnegativas EVI 2002-2017")
Plt-anomneg
```

### Muchísimas opciones de análisis mediante algoritmos de aprendizaje automático

La mayoría requiere transformar el stack multitemporal a otra estructura de datos

### Paquete cluster M Maechler


### Paquete kohonen R Wehrens


### Paquete tmap M Tennekes https://github.com/mtennekes/tmap


### ¡Visualización con Leaflet!


# Muchas gracias


Priscilla Minotti
priscilla.minotti@gmail.com
pminotti@unsam.edu.ar
Tweeter @pmnatural
https://t.me/rspatial_es


